### ISSUE TITLE
Too fast

### ISSUE THREAD

**Issue by mikaelmello** [DanielHe4rt/bbbot#11]
![image](https://user-images.githubusercontent.com/17488630/77276913-87f58780-6c9a-11ea-9a57-f1fbc6fcc062.png)

**Comment by Lucasark** [comment]
Basta aumentar o tempo de click,ou coloca um try catch da issue aberta #8

**Comment by Lucasark** [comment]
Como você colocou o mouse para funcionar na primeira posição? @mikaelmello

**Comment by mikaelmello** [comment]
> �Basta aumentar o tempo de click,ou coloca um try catch da issue aberta #8

Não funciona, a Globo mudou o formato de quando isso aparece e quebra o parsing do DOM.

> Como você colocou o mouse para funcionar na primeira posição? @mikaelmello

![image](https://user-images.githubusercontent.com/17488630/77291597-5b069c00-6cbd-11ea-98fb-8ed518f72884.png)

**Comment by Lucasark** [comment]
Aumentei a frequência de 30 milissegundos para 1500 e ao meu ver ficou sem problemas, usando o try catch resolvi o paralelismo. Estou debugando do porque quando acha a mochila não coloca no indexe.

**Comment by mikaelmello** [comment]
![image](https://user-images.githubusercontent.com/17488630/77293115-7030fa00-6cc0-11ea-965a-d207841e3e84.png)

Parece que tem mochilas diferentes agora

**Comment by Lucasark** [comment]
De fato! As imagens estão tendo ~3 para cada chave-palavra, achei 4 tipos de mochilas, 3 tipos de lixeira, etc...
Será que agora só resolve com o tensorflow? Ou, pode colocar para sempre chutar um lugar, percebi que se ficar chutando, cai em block com tempo na pagina apresentando um loading "infinito"

**Comment by Suburbanno** [comment]
Já tem alguma solução?

**Comment by Robertorosmaninho** [comment]
> Aumentei a frequência de 30 milissegundos para 1500 e ao meu ver ficou sem problemas, usando o try catch resolvi o paralelismo. Estou debugando do porque quando acha a mochila não coloca no indexe.

como resolveu o paralelismo?

**Comment by riccihenrique** [comment]
Se clicar no meio da imagem sempre, ela funciona

**Comment by alyleite** [comment]
> Se clicar no meio da imagem sempre, ela funciona

Você diz clicar no meio das imagens?

**Comment by riccihenrique** [comment]
> > Se clicar no meio da imagem sempre, ela funciona
> 
> Você diz clicar no meio das imagens?

Bloquearam minha conta com isso kkkk eu estava clicando sempre na imagem do meio, independente do que fosse pedido. Geralmente na 5 vez a imagem do meio era a correta, porém minha conta foi bloqueada

**Comment by alyleite** [comment]
> > > Se clicar no meio da imagem sempre, ela funciona
> > 
> > 
> > Você diz clicar no meio das imagens?
> 
> Bloquearam minha conta com isso kkkk eu estava clicando sempre na imagem do meio, independente do que fosse pedido. Geralmente na 5 vez a imagem do meio era a correta, porém minha conta foi bloqueada

hehe entendi. Na vdd estava rodando outro bot aqui que reconhece a imagem e tbm bloqueram a minha conta

**Comment by Lucasark** [comment]
Estou pegando uma abordagem com o Tensorflow, inspirado em um vídeo no YT que vi. Talvez tenha bons resultados

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.
