### ISSUE TITLE
Refresh Captchar

### ISSUE THREAD

**Issue by PedroPCardoso** [DanielHe4rt/bbbot#13]
O robo fica dando refresh no captcha e não vota.

**Comment by dezin1** [comment]
mesmo problema aqui, o capcha está com alguma diferença da semana passada?

**Comment by matheustavaresdev** [comment]
Parece que foi consertado mas quebrou de novo. Acho que a globo andou mudando os codigos

**Comment by Lucasark** [comment]
Por favor, ver a #11 . Estamos lidando com o problema de comparação dos base64

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.
