### ISSUE TITLE
Recarregar imagens SPAM

### ISSUE THREAD

**Issue by matheustavaresdev** [DanielHe4rt/bbbot#16]
Agora o site da globo esta detectando spam, entao tempos que recarregar as imagens. Se der um teiout e tentar ver se esse botao de recarregar as imagens esta disponivel de x em x segundos e clicar nele, o bot vai rodar pra sempre!! parabens de qualquer forma.

![Screen Shot 2020-03-30 at 19 49 27](https://user-images.githubusercontent.com/36674530/77969279-c1904900-72bf-11ea-8719-56f1ec242329.png)
![Screen Shot 2020-03-30 at 19 49 32](https://user-images.githubusercontent.com/36674530/77969282-c3f2a300-72bf-11ea-8697-ca1ed579a60f.png)

**Comment by thadeubrito** [comment]
olha onde os caras chegaram hahahahah. projeto legal pra pegar umas ideias!

**Comment by matheustavaresdev** [comment]
Fechado a favor de https://github.com/DanielHe4rt/bbbot/issues/11
