### ISSUE TITLE
Nao loga!

### ISSUE THREAD

**Issue by paulorobsant** [DanielHe4rt/bbbot#18]
Tentei logar varias vezes e nao vai

**Comment by Robertorosmaninho** [comment]
manda print do erro

**Comment by jpbraganca** [comment]
Ao executar "run-server.bat" e pelo "run-server-login.bat", coloco o email e senha, e o cmd simplesmente fecha

**Comment by Limongi2018** [comment]
Mesmo erro aqui.

**Comment by Limongi2018** [comment]
[https://ibb.co/Qrkm923](url)

**Comment by Limongi2018** [comment]
![erro](https://user-images.githubusercontent.com/62917039/77975810-200df500-72c9-11ea-874a-a6cc4fd74b89.jpg)

**Comment by Robertorosmaninho** [comment]
> Ao executar "run-server.bat" e pelo "run-server-login.bat", coloco o email e senha, e o cmd simplesmente fecha

faz o seguinte, no terminal escreve "node src/index.js manu emai@sever.com senha"

**Comment by Robertorosmaninho** [comment]
@paulorobsant se conseguiu resolver o problema, por favor feche a issue.

**Comment by Limongi2018** [comment]
Nao consegui.

**Comment by Robertorosmaninho** [comment]
instalou o node? Panda print novamente, por favor

**Comment by Limongi2018** [comment]
- 

- 

- [ ] 
![erroo](https://user-images.githubusercontent.com/62917039/77976390-dfaf7680-72ca-11ea-8fc4-47a88a23eb98.jpg)

**Comment by Limongi2018** [comment]
Instalei

**Comment by viperoz** [comment]
aqui da o mesmo problema do Limongi2018

**Comment by paulorobsant** [comment]
Ainda nao ta dando, fiz um procedimento que tem nos pull request sobre script no windows 10 e funcionou, porem agora deu outro problema

**Comment by Limongi2018** [comment]
Consegui. Mas so vota uma vez e para.

**Comment by paulorobsant** [comment]
Exatamente! ja ate abri um issue sobre

**Comment by arthurpalauro** [comment]
aqui tb estou com o mesmo problema. Onde escrevo node src/index.js manu? No run-server???

> > Ao executar "run-server.bat" e pelo "run-server-login.bat", coloco o email e senha, e o cmd simplesmente fecha
> 
> faz o seguinte, no terminal escreve "node src/index.js manu [emai@sever.com](mailto:emai@sever.com) senha"

**Comment by spikejones** [comment]
o meu dps q eu boto a senha o cmd fecha

**Comment by jpbraganca** [comment]
> 
> 
> aqui tb estou com o mesmo problema. Onde escrevo node src/index.js manu? No run-server???
> 
> > > Ao executar "run-server.bat" e pelo "run-server-login.bat", coloco o email e senha, e o cmd simplesmente fecha
> > 
> > 
> > faz o seguinte, no terminal escreve "node src/index.js manu [emai@sever.com](mailto:emai@sever.com) senha"

Acessa a pasta do projeto pelo cmd, ai tu roda o "node src/index.js manu emai@sever.com senha"

**Comment by arthurpalauro** [comment]
![fdgrgrdg](https://user-images.githubusercontent.com/62918026/77977741-e04e0a00-72d6-11ea-80ff-fb8b1a6483bb.png)

**Comment by arturdirenna** [comment]
mesmo problema @arthurpalauro

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.
