### ISSUE TITLE
Vota so uma vez e para!

### ISSUE THREAD

**Issue by paulorobsant** [DanielHe4rt/bbbot#19]
Vota so uma vez e para!

**Comment by Robertorosmaninho** [comment]
@DanielHe4rt

**Comment by mateuspestana** [comment]
Mesma coisa aqui. Quando acerta, não retorna à votação, e é preciso ir lá e clicar no participante desejado de novo.

**Comment by rfgatto** [comment]
Mesma coisa aqui 

![foto erro](https://user-images.githubusercontent.com/10201343/77979323-b991d280-72da-11ea-8ed2-ca9aa997a842.png)

**Comment by paulorobsant** [comment]
é pq vc ta votando na manu, por isso o erro

**Comment by cunha981** [comment]
Alguém conseguiu resolver? @paulorobsant @Robertorosmaninho @mateuspestana @rfgatto @DanielHe4rt 
Vi que toSave está ficando vazio.

**Comment by thiagonl** [comment]
Mesma coisa aqui, vota a primeira vez e para

**Comment by Liip3Lim4** [comment]
Foda que tá funcionando de boa porém não fica em loop, vota 1x e não vota mais.

**Comment by thiagonl** [comment]
> Foda que tá funcionando de boa porém não fica em loop, vota 1x e não vota mais.

Exatamente o que aconteceu aqui. Tentei com os 3 participantes e o que acontece é o mesmo.

**Comment by jonniehenrique** [comment]
O @DanielHe4rt postou no instagram dele que a Globo usou o código do bot para melhorar o código deles, por isso inviabilizou o bot, não tá funcionando mais. Maaaas.. ele falou tbm que consegue resolver fácilmente isso.

**Comment by rfgatto** [comment]
Facilmente? Então agiliza ai @DanielHe4rt !!! Enqt a gente espera tem uma menina de 12 anos rindo da gente e votando com celular, tablete, 7 abas no computador!

**Comment by luccasbeck** [comment]
revoteBtn: '/html/body/div[2]/div[4]/div/div[3]/div/div/div[1]/div[2]/button',

Isso aqui precisa ser mudado pro novo caminho do botão de tentar novamente

**Comment by paulorobsant** [comment]
qual o caminho entao?

**Comment by MarioDunda** [comment]
> revoteBtn: '/html/body/div[2]/div[4]/div/div[3]/div/div/div[1]/div[2]/button',
> 
> Isso aqui precisa ser mudado pro novo caminho do botão de tentar novamente

Qual caminho?

**Comment by BrunoKrugel** [comment]
bbbot-master\bbbot-master\src\config\contents.js

**Comment by paulorobsant** [comment]
o carminho do botao

> bbbot-master\bbbot-master\src\config\contents.js

do botao cara

**Comment by paulorobsant** [comment]
> bbbot-master\bbbot-master\src\config\contents.js

o caminho do botao

**Comment by vbmsouza** [comment]
mesmo problema

**Comment by matheustark** [comment]
Como faz para alterar o botão revoteBtn pro componente correto na tela?

**Comment by paulorobsant** [comment]
> Como faz para alterar o botão revoteBtn pro componente correto na tela?

to testando aqui

**Comment by riccihenrique** [comment]
> Como faz para alterar o botão revoteBtn pro componente correto na tela?

To testando aqui também

**Comment by matheustark** [comment]
Tbm to tentando, se alguém descobrir manda aí

**Comment by arthurpalauro** [comment]
> bbbot-master\src\config\contents.js

manda print do caminho pf

**Comment by MarioDunda** [comment]
> > bbbot-master\src\config\contents.js
> 
> manda print do caminho pf

 '/html/body/div[2]/div[4]/div/div[3]/div/div/div[1]/div[2]/button' esse é o caminho eu fui la no site da globo e olhei, ele ta certo

**Comment by playeredhelice** [comment]
> revoteBtn: '/html/body/div[2]/div[4]/div/div[3]/div/div/div[1]/div[2]/button',
> 
> Isso aqui precisa ser mudado pro novo caminho do botão de tentar novamente

Parece não ser esse o problema, pq o caminho do componente na página de votação é o mesmo que consta no código.

**Comment by vbmsouza** [comment]
crtz? vou dar uma conferida aq

**Comment by riccihenrique** [comment]
O botão de login parou de funcionar aqui

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.

**Comment by juniorterin** [comment]
linha 99 em utils.js

trocar para
const retryBtn = await page.waitForSelector('._3VpV6myQ0E-1rsgh9PoeaN');

**Comment by riccihenrique** [comment]
> linha 99 em utils.js
> 
> trocar para
> const retryBtn = await page.waitForSelector('._3VpV6myQ0E-1rsgh9PoeaN');

Não deu não amigo

**Comment by matheustark** [comment]
Aqui não rolou

Em ter, 31 de mar de 2020 às 01:37, Ademir Terin Junior <
notifications@github.com> escreveu:

**Comment by charlescarneiro** [comment]
Galera, o caminho mudou mesmo. O prblema é que nao sei qual a posição do "DIV". por enquanto o caminho novo é: '/html/body/div[2]/div[4]/div/div[1]... " falta o resto, porque a proxima div nao sei qual a posição dela pq só tem "DIV" limpa e seca.

**Comment by riccihenrique** [comment]
Galera, na função revote, deixem assim:
const revote = victim => async page => {
  await new Promise(resolve => setTimeout(resolve, 400));
  const retryBtn = await page.waitForXPath(XPathContents.revoteBtn);
  setTimeout(_ => {retryBtn.click();setTimeout(_ => vote(victim)(page), 1500) }, 1000)
await new Promise(resolve => setTimeout(resolve, 400));
};

**Comment by Liip3Lim4** [comment]
@riccihenrique show, com essa modificação realmente passou a funcionar corretamente, ele tenta o captcha até acertar e vota novamente!

**Comment by riccihenrique** [comment]
Foda que como ele erra muito, começa a ficar lendo depois de um tempo. Se alguém conseguir resolver o problema das imagens da um salve
