### ISSUE TITLE
não consigo abrir o bot

### ISSUE THREAD

**Issue by spikejones** [DanielHe4rt/bbbot#21]
Abro o runserver, preencho os dados da conta e quando dou enter não aparece nada

**Comment by BrunoKrugel** [comment]
Olha esse fix aqui e nao esquece de usar
`npm install`
https://github.com/DanielHe4rt/bbbot/pull/17

**Comment by vbmsouza** [comment]
me too

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.
