### ISSUE TITLE
Não é possível escolher em quem votar apenas rodando o run-server.bat

### ISSUE THREAD

**Issue by tembra** [DanielHe4rt/bbbot#23]
O prompt de comando reconhece a barra vertical  `|` como pipe e tenta executar o comando `manu`, obviamente inexistente.

https://github.com/DanielHe4rt/bbbot/blob/da24af245ef70f48f60ee22db4b28955a23e9802/run-server.bat#L4

```
'manu' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
```

**Comment by paulorobsant** [comment]
Vai na aba Pull Request e tenta usar a soluçao sobre resolver script no windows 10

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.
