### ISSUE TITLE
o cmd fecha dps do login

### ISSUE THREAD

**Issue by arthurpalauro** [DanielHe4rt/bbbot#24]
depois que boto o email e senha e dou enter o cmd fecha e nada acontece

**Comment by spikejones** [comment]
mesmo problema

**Comment by fabioselau077** [comment]
Se fechar após digitar a senha, entra na pasta pelo Prompt de Comando ("CMD") e digita o comando: "node src/index.js manu seuemail@gmail.com SuaSenha", sem as aspas. Após isso será iniciado o navegador Chromium (parecido com o Chrome) e o bot entrará em funcionamento.

**Comment by vpasa** [comment]
coloquei o comando porem deu erro no modulo "c:user\vinicius\src\index.js

**Comment by vpasa** [comment]
coloquei o comando porem deu erro no modulo "c:\user\vinicius\src\index.js"

**Comment by spikejones** [comment]
[https://imgur.com/a/6kCOlU6](url)

**Comment by viperoz** [comment]
> Se fechar após digitar a senha, entra na pasta pelo Prompt de Comando ("CMD") e digita o comando: "node src/index.js manu [seuemail@gmail.com](mailto:seuemail@gmail.com) SuaSenha", sem as aspas. Após isso será iniciado o navegador Chromium (parecido com o Chrome) e o bot entrará em funcionamento.

não funciona isso aqui, da esse erro
![erro](https://user-images.githubusercontent.com/62910791/77980878-e0520800-72de-11ea-9e8e-a4b4a2a8c211.jpg)

consigo executar o bot pelo run-server, mas ele só vota 1 vez e para!

**Comment by spikejones** [comment]
https://imgur.com/a/6kCOlU6

**Comment by spikejones** [comment]
aqui também não ta funcionando

**Comment by rickrribeiro** [comment]
> > Se fechar após digitar a senha, entra na pasta pelo Prompt de Comando ("CMD") e digita o comando: "node src/index.js manu [seuemail@gmail.com](mailto:seuemail@gmail.com) SuaSenha", sem as aspas. Após isso será iniciado o navegador Chromium (parecido com o Chrome) e o bot entrará em funcionamento.
> 
> não funciona isso aqui, da esse erro
> ![erro](https://user-images.githubusercontent.com/62910791/77980878-e0520800-72de-11ea-9e8e-a4b4a2a8c211.jpg)
> 
> consigo executar o bot pelo run-server, mas ele só vota 1 vez e para!

vei tira isso da system32 antes que voce faça algo errado e acabe com seu pc kkkk

**Comment by rickrribeiro** [comment]
> aqui também não ta funcionando

Explica o problema

**Comment by rickrribeiro** [comment]
> aqui também não ta funcionando

tenta em outra pasta sem ser a sys32

**Comment by foramanucrl** [comment]
Alguém sabe como resolver?  

Error: Browser is not downloaded. Run "npm install" or "yarn install"
    at ChromeLauncher.launch

**Comment by viperoz** [comment]
> > aqui também não ta funcionando
> 
> tenta em outra pasta sem ser a sys32

aa é, esqueci de entrar na pasta, ta rodando agora.
mas é normal isso? erra muito a imagem do captcha e só fica dando voto não computado

**Comment by viperoz** [comment]
![erro2](https://user-images.githubusercontent.com/62910791/77981820-3de75400-72e1-11ea-8b62-9a9b36a85e13.jpg)

**Comment by AprendendoRapido** [comment]
O que vc mudou "viperoz" ?

**Comment by vpasa** [comment]
![kokokokok](https://user-images.githubusercontent.com/62920384/77982151-ff9e6480-72e1-11ea-9e86-b7907027c8c6.png)

**Comment by viperoz** [comment]
Ah e quando o bot acerta a imagem catpcha, ele para..

**Comment by spikejones** [comment]
VIPEROZ, COMO FAZ PRA O BOT COMEÇAR A VOTAR

**Comment by AprendendoRapido** [comment]
Manda um print VIPEROZ

**Comment by foramanucrl** [comment]
> Error: Browser is not downloaded. Run "npm install" or "yarn install"
> at ChromeLauncher.launch

Resolvido. Executei npm i puppeteer

**Comment by foramanucrl** [comment]
> Ah e quando o bot acerta a imagem catpcha, ele para..

Segue o mesmo aqui. Alguem ja resolveu?

**Comment by neryvini** [comment]
Aqui a mesma coisa, faz o primeiro voto e depois para.

**Comment by arthurpalauro** [comment]
[
![fdfftrdfgfdgghvgffg](https://user-images.githubusercontent.com/62918026/77982932-f1514800-72e3-11ea-94af-41dd3bf619b4.png)    aqui ta assim
](url)

**Comment by arturdirenna** [comment]
mesmo problema. coloco o node src/index.js manu e dá erro

**Comment by francisco-santana** [comment]
aqui quando o bot acerta a imagem catpcha, ele para tbm...

**Comment by arthurpalauro** [comment]
consegui, tava acessando pasta errada, mas ele vota 1 vez e para

**Comment by AprendendoRapido** [comment]
Qual pasta errada?

**Comment by arthurpalauro** [comment]
esqueci de botar pro desktop e pra pasta q tava

**Comment by arturdirenna** [comment]
o que eu escrevo pra ele direcionar o comando pro desktop>pasta?

**Comment by arthurpalauro** [comment]
https://medium.com/@adsonrocha/como-abrir-e-navegar-entre-pastas-com-o-prompt-de-comandos-do-windows-10-68750eae8f47 usa esse site aq se vc nao conseguir abrir a pasta pelo cmd

**Comment by spikejones** [comment]
qual pasta????

**Comment by arthurpalauro** [comment]
na que ta o bot

**Comment by arturdirenna** [comment]
como eu direciono o comando para a pasta a partir do cmd?

**Comment by viperoz** [comment]
gente, pra que querem entrar na pasta certa e rodar? kk nao adianta, ta bugado, fica errando as imagens do captcha e quando acerta o bot para.

**Comment by guiicardozo** [comment]
> 
> 
> Ah e quando o bot acerta a imagem catpcha, ele para..

Conseguiu arrumar isso?

**Comment by arturdirenna** [comment]
consegui mas ele para quando acerta o capcha. será que ele ta tentando arrumar pra automatizar?

**Comment by guiicardozo** [comment]
> 
> 
> consegui mas ele para quando acerta o capcha. será que ele ta tentando arrumar pra automatizar?

Pra mim, para depois que acerta o captcha. Acho que ele falou que não ia mais mexer no bot por medo da globo :(

**Comment by torrigo** [comment]
galera, nao sei nada. alguem me da um help?

**Comment by arturdirenna** [comment]
nem ta valendo a pena. bot erra muito o captcha e nao ta automatico. aguardar pra ver se ele atualiza ae

**Comment by torrigo** [comment]
: (

**Comment by viperoz** [comment]
ele não vai mais atualizar. postou storie no instagram que a globo usou o código pra melhorar o sistema de segurança da votaçao. mas quem manja consegue burlar facilmente

**Comment by arturdirenna** [comment]
quem manja manda o outro aí hahahahhaha

**Comment by torrigo** [comment]
kkkkkkkkkkkkk

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.

**Comment by torrigo** [comment]
f

**Comment by guiicardozo** [comment]
Alguém ajuda nois ae!!
