### ISSUE TITLE
handler[0].click();

### ISSUE THREAD

**Issue by ecilaa** [DanielHe4rt/bbbot#8]
Daniel arruma isso ai amigao

handler[0].click();
               ^

TypeError: Cannot read property 'click' of undefined
    at Timeout.setTimeout [as _onTimeout] (/home/vortex/bbbot/helper.js:130:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by seltonfiuza** [comment]
Na linha 129 a 131 do helper.js substitui por isso:

```
setTimeout(() => {
    try {
      handler[0].click();
    } catch (error) {
      console.log('Error, trying again')
      refreshCaptcha( page, xpath)
    }
  }, 30);
```

**Comment by DanielHe4rt** [comment]
Rapaziada, seguinte. Pro bot rodar, é necessário que vocês subam um servidor pra armazenar as vertentes do bot e começarem a computar novas possibilidades.

Não irei dar mais suporte ao bot, porém vocês podem forkar o projeto e começar a fazer do jeito que vocês quiserem. 

Estarei fechando as issues e qualquer dúvida técnica para subir o bot novamente, podemos discutir no discord caso você saiba o que esteja fazendo.
